apiVersion: apps/v1
kind: Deployment
metadata:
  name: next-docker-base
spec:
  replicas: 1
  selector:
    matchLabels:
      app: next-docker-base
  template:
    metadata:
      labels:
        app: next-docker-base
    spec:
      containers:
        - name: next-docker-base
          image: ghcr.io/fahmialis/next-docker-base:${IMAGE_TAG}
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"